### ISSUE TITLE
Could you please provide the binary train/test you used in your paper

### ISSUE THREAD

**Issue by GAO-Rachel** [MarkWuNLP/MultiTurnResponseSelection#12]
Hi Wu,

We tried to carefully replicate your work in tensorflow and the performances are awesome, however, our model is still 3-4% lower compared to you reported in your paper. 

We suspect the reason is that the word embedding for initialization we used is different to yours. Thus I wonder if you could provide the train/test binary file that you used in your code?

Best wishes,
Xijuan

**Comment by MarkWuNLP** [comment]
Sorry for late reply.  Word Embedding is very very important for this task.

200d embedding and corpus is saved at https://1drv.ms/u/s!AtcxwlQuQjw1jF0bjeaKHEUNwitA

**Comment by yangliuy** [comment]
@GAO-Rachel @MarkWuNLP I also re-implement the SMN model with Tensorflow/Keras following the descriptions in the ACL paper. The current performances are similar to what @GAO-Rachel got, which are %2 - %3 lower than the results in the paper. I used the training data of UDC to get the 200 dimensional word vectors and all the hyper-parameters are the same with the descriptions in the paper. I am investigating the reason behind this. If you have any ideas on this problem or reproduced the results in the paper, feel free to add your comments here. Thank you!

**Comment by MarkWuNLP** [comment]
Liu Yang has reimplemented by work based on provided word embedding file

**Comment by yangliuy** [comment]
@MarkWuNLP Thank you for sending the TF version of SMN! I only successfully run the TF version insteads of this theano version. Meanwhile, could you reply to my following questions in the Email ? Thank you! 

1. Could you please describe how you generate the file embedding.pkl ? What is the corresponding word dictionary  file (word_id -> word) ? Since I need to know the corresponding term for each line in this file if I use this embedding file.

2. I noticed the following setting on the word_embeddings you used:
word_embeddings = tf.get_variable('word_embeddings_v', shape=(self.total_words,self.word_embedding_size), dtype=tf.float32, trainable=False)

which means you didn't fine tune the word embedding during model training. Is this setting the same with the setting of the reported results in the paper ?

3. The vocabulary size is 434511, which is four times larger than mine. I filtered all the terms that appear less than 5 times during the data preprocess and word embedding training process. Did you keep all the terms in these two processes ? Do you have the scripts which generate the 4 .pkl files from the raw input data of Ubuntu (train.txt/valid.txt/test.txt) ?

**Comment by chenf99** [comment]
@yangliuy I have the same question as you, could you please tell me about @MarkWuNLP 's response?Thank you!
